### ISSUE TITLE
UI is acceptable, but UX is ridiculous

### ISSUE THREAD

**Issue by TheAndroidMaster** [TheAndroidMaster/MediaNotification#14]
Two changes need to happen before this app is useful to the muggles:
1. split the main screen into two tabs, one for the README and one for the settings, since it's apparently too much work to scroll to the bottom of the page
2. add a tutorial/quick setup page that explains the app in a more intuitive manner and offers 'preset' setting configurations

**Comment by TheAndroidMaster** [comment]
I'll need to add a tutorial or something to this fragment to explain how it works later, since currently it just has a 'set default' button on every installed app with no context

**Comment by fython** [comment]
You can refer to Android built-in SetupWizard UI for Tutorial UI. Or try out this library: [OmicoAndroidLibrary/SetupWizardLib](https://github.com/OmicoAndroidLibrary/SetupWizardLib)

**Comment by TheAndroidMaster** [comment]
Okay, this is fixed now.
