### ISSUE TITLE
Display play button when music is paused

### ISSUE THREAD

**Issue by deletescape** [TheAndroidMaster/MediaNotification#15]
Android Version: 7.1.1
Music Player: Spotify
After pausing the music (the notification also says "Paused" at the top) the pause/play button still displays the pause button, changing this to a play button would make it look more like normal media notifications.

**Comment by TheAndroidMaster** [comment]
Can't reproduce this on an emulator or physical device. Is it possible that there could be another music player sending broadcasts that are interfering with Spotify's? If by any chance you could include the logs with tag `MediaReceiver` that would be a huge help.

**Comment by deletescape** [comment]
Can't reproduce it anymore myself, after being able to get this behavior for hours, it suddenly worked right after reporting here, would get logs in case it ever happens again, but I'll close it for now
