### ISSUE TITLE
Service stops when app is closed

### ISSUE THREAD

**Issue by jahirfiquitiva** [TheAndroidMaster/MediaNotification#2]
Also, for some reason, it was only working while I had it connected to debug :/

**Comment by TheAndroidMaster** [comment]
You said this has stopped happening, right? If so can I close this issue? :P

**Comment by jahirfiquitiva** [comment]
@TheAndroidMaster 
Yep, now it's the opposite. It never stops when music is stopped. 😂

**Comment by TheAndroidMaster** [comment]
@jahirfiquitiva see #5 😁
