### ISSUE TITLE
Integrating into Music App

### ISSUE THREAD

**Issue by theoth267** [TheAndroidMaster/MediaNotification#29]
I was curious, why wouldnt you just integrate it into a music player, it should work flawlessly if its coded into the player itself and im sure a music player with oreo style notifications would get loads of downloads, maybe even sales.

**Comment by TheAndroidMaster** [comment]
Music players take too long to make. [Pasta Music](https://github.com/TheAndroidMaster/Pasta-Music) is proof of that (last commit was over a year ago, started too many new projects and ran out of time to work on it). I guess I _could_ make one based on [Phonograph](https://github.com/kabouzeid/Phonograph) if I really wanted to, but even then the release date wouldn't be anytime soon.

However, if the owner of an existing music player wanted to implement notifications like these into their own music player, they would be very welcome to - it's open source for a reason.

**Comment by TheAndroidMaster** [comment]
I'm guessing your question has been answered? Going to close this issue for now.
